version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip3 install -r requirements.txt --user
      - run: autopep8 --in-place --aggressive --recursive .
      - run: python3 manage.py test