version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/weird-text
    steps:
      - checkout
      - run: pip3 install -r requirements.txt --user
      - run: autopep8 --in-place --aggressive --recursive .
      - run: python3 manage.py test
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
